#ifndef VOIP_AUDIO_DEVICE_AUDIO_DEVICE_CONFIG_H_
#define VOIP_AUDIO_DEVICE_AUDIO_DEVICE_CONFIG_H_

// Enumerators
//
enum { kAdmMaxIdleTimeProcess = 1000 };
enum { GET_MIC_VOLUME_INTERVAL_MS = 1000 };


#endif  //VOIP_AUDIO_DEVICE_AUDIO_DEVICE_CONFIG_H_

