
#ifndef VOIP_SYSTEM_WRAPPERS_INTERFACE_CONSTRUCTOR_MAGIC_H_
#define VOIP_SYSTEM_WRAPPERS_INTERFACE_CONSTRUCTOR_MAGIC_H_

#include "audio_engine/include/typedefs.h"
#endif  // VOIP_SYSTEM_WRAPPERS_INTERFACE_CONSTRUCTOR_MAGIC_H_
